// Semua bank soal game — data statis lokal, gak butuh API/internet.

const ASAHOTAK = [
  { q: "Aku punya kepala dan ekor tapi gak punya badan. Aku apa?", a: "koin" },
  { q: "Semakin banyak diambil dari aku, aku malah semakin besar. Aku apa?", a: "lubang" },
  { q: "Apa yang naik tapi gak pernah turun?", a: "umur" },
  { q: "Punya kunci tapi gak bisa buka pintu. Apa itu?", a: "piano" },
  { q: "Rumah apa yang bisa jalan?", a: "siput" },
  { q: "Berjalan tanpa kaki, punya sayap tapi gak bisa terbang. Apa itu?", a: "kapal" },
  { q: "Aku selalu datang tapi gak pernah sampai. Aku apa?", a: "hari esok" },
  { q: "Apa yang punya banyak gigi tapi gak bisa gigit?", a: "sisir" },
  { q: "Apa yang bisa diisi penuh tapi tetap punya banyak lubang?", a: "spons" },
  { q: "Punya leher tapi gak punya kepala. Apa itu?", a: "botol" },
  { q: "Benda apa yang selalu lari tapi gak punya kaki?", a: "jam" },
  { q: "Apa yang semakin basah saat dia makin mengeringkan?", a: "handuk" },
  { q: "Bisa dipegang pakai tangan kiri, tapi gak bakal bisa dipegang pakai tangan kanan. Apa itu?", a: "sikut kanan" },
  { q: "Benda apa yang kalau dipotong malah makin tinggi?", a: "celana" },
  { q: "Aku bisa tajam tanpa dipasang mata, dan aku bisa patah tanpa disentuh. Aku apa?", a: "janji" },
  { q: "Jika ada 5 burung di dahan dan 1 ditembak, berapa burung yang tersisa?", a: "0" },
  { q: "Punya jari tapi gak punya kuku atau daging. Apa itu?", a: "sarung tangan" },
  { q: "Makin banyak kamu melihatku, makin sedikit yang bisa kamu lihat. Apa itu?", a: "kegelapan" },
  { q: "Kalau ditaruh berdiri jatuh, kalau diputar berjalan. Apa itu?", a: "roda" },
  { q: "Bisa terbang tanpa sayap, menangis tanpa mata. Apa itu?", a: "awan" },
  { q: "Selalu berada di depan kamu tapi gak pernah bisa kamu lihat. Apa itu?", a: "masa depan" },
  { q: "Punya mata tapi gak bisa melihat. Apa itu?", a: "jarum" },
  { q: "Kota apa yang tidak punya bangunan, sungai tanpa air, dan gunung tanpa batu?", a: "peta" },
  { q: "Semakin cepat kamu lari, semakin sulit kamu mengejarku. Apa itu?", a: "nafas" },
  { q: "Benda apa yang kalau dipanggil selalu memantulkan suara kita?", a: "gema" },
  { q: "Ringan seperti bulu, tapi manusia terkuat pun gak bisa menahannya lebih dari beberapa menit. Apa itu?", a: "nafas" },
  { q: "Aku lahir di air, tapi kalau dikembalikan ke air aku hilang. Aku apa?", a: "garam" },
  { q: "Benda apa yang dibeli untuk makan tapi gak pernah dimakan?", a: "piring" },
  { q: "Punya 4 kaki di pagi hari, 2 kaki di siang hari, dan 3 kaki di malam hari. Siapa itu?", a: "manusia" },
  { q: "Semakin banyak kamu membuatku, semakin banyak yang kamu tinggalkan di belakang. Apa itu?", a: "langkah kaki" },
  { q: "Aku tidak bernapas, tapi aku butuh udara. Aku tidak punya mulut, tapi air bisa membunuhku. Aku apa?", a: "api" },
  { q: "Benda apa yang bisa membawa kamu keliling dunia tanpa meninggalkan sudut ruangan?", a: "prangko" },
  { q: "Punya banyak wajah, tapi tidak punya kepala atau tubuh. Apa itu?", a: "dadu" },
  { q: "Apa yang bisa kamu dengar tapi tidak bisa dilihat atau disentuh, dan hanya berbicara saat kamu berbicara?", a: "gema" },
  { q: "Benda apa yang selalu datang tapi tidak pernah tiba?", a: "besok" },
  { q: "Aku bisa pendek atau panjang, bisa dibuat atau dihancurkan, tapi tidak bisa disentuh. Aku apa?", a: "cerita" },
  { q: "Punya banyak kamar tapi tidak punya pintu atau jendela. Apa itu?", a: "sarang lebah" },
  { q: "Semakin tinggi aku berdiri, semakin pendek bayanganku di siang hari. Apa itu?", a: "tiang" },
  { q: "Benda apa yang jika dipecahkan justru menjadi lebih berguna?", a: "telur" },
  { q: "Apa yang punya kulit di luar dan isi di dalam, tapi kalau dikupas bikin orang menangis?", a: "bawang" },
  // Tambahan Masif Baru
  { q: "Semakin kamu memotongku, semakin panjang aku jadinya. Apa itu?", a: "parit" },
  { q: "Punya 88 kunci tapi gak bisa membuka satu pun kunci gembok. Apa itu?", a: "piano" },
  { q: "Apa yang selalu memiliki jawaban tanpa pernah diajukan pertanyaan?", a: "siri" },
  { q: "Bisa melintasi laut tanpa basah. Apa itu?", a: "bayangan" },
  { q: "Punya punggung tapi gak punya perut. Apa itu?", a: "buku" },
  { q: "Benda apa yang kalau dibanting pecah, tapi kalau disenyumin balik tersenyum?", a: "cermin" },
  { q: "Siapa yang membuatku tidak membuangku, siapa yang membeliku tidak memakainya, siapa yang memakainya tidak mengetahuinya?", a: "peti mati" },
  { q: "Aku punya banyak lubang tapi bisa menampung air. Apa itu?", a: "spons" },
  { q: "Jika dikelilingi pagar aku ada di tengah, jika dipotong di tengah aku ada dua. Apa aku?", a: "angka delapan" },
  { q: "Apa yang makin lama makin tebal di perpustakaan lama tapi bukan buku?", a: "debu" }
];

const TEBAKTEBAKAN = [
  { q: "Kenapa ayam gak boleh main ke sirkus?", a: "nanti diakuin bebek" },
  { q: "Apa bedanya rumput sama semut?", a: "kalau rumput dipangkas, kalau semut dipijak" },
  { q: "Kenapa telepon gak pernah masuk angin?", a: "karena ada kartunya" },
  { q: "Kenapa kalkulator gak pernah cemburu?", a: "karena dia selalu dapat hasil yang pasti" },
  { q: "Hewan apa yang jalannya paling lambat sedunia?", a: "keong" },
  { q: "Kenapa ikan gak suka main basket?", a: "takut kena net" },
  { q: "Lemari apa yang bisa dimasukkan ke dalam kantong?", a: "lemarihan" },
  { q: "Sayur apa yang bisa menyanyi?", a: "kolplay" },
  { q: "Buah apa yang paling tidak sopan?", a: "mangga" },
  { q: "Nasi apa yang paling melelahkan?", a: "nasional" },
  { q: "Kota apa yang paling banyak bapak-bapaknya?", a: "purwokerto" },
  { q: "Pintu apa yang didorong sama 5 orang tetap gak bisa terbuka?", a: "pintu geser" },
  { q: "Gajah naik motor kelihatan apanya?", a: "bohongnya" },
  { q: "Ayam apa yang paling besar di dunia?", a: "ayam semesta" },
  { q: "Batu apa yang paling berat di dunia?", a: "batuk bertahak" },
  { q: "Pohon apa yang paling sering muncul di hari natal?", a: "pohon cemara" },
  { q: "Penyanyi luar negeri yang suka keroyokan?", a: "bruno mars" },
  { q: "Susu apa yang bisa ditonton?", a: "susumu" },
  { q: "Rambut sama hitam, tapi kenapa minumnya beda?", a: "karena beda haus" },
  { q: "Mobil apa yang bisa bikin pusing?", a: "mobilang kangen tapi bukan siapa siapa" },
  { q: "Ikan apa yang paling matre?", a: "ikan komet" },
  { q: "Ditembak ke bawah tapi kena yang di atas. Apa itu?", a: "kentut" },
  { q: "Rusa apa yang gak bisa jalan?", a: "rusak" },
  { q: "Kenapa kura-kura lambat?", a: "karena bawa rumah sendiri" },
  { q: "Buah apa yang berbahaya buat keselamatan?", a: "buahncurkan" },
  { q: "Tahu apa yang paling besar?", a: "tahu isi dunia" },
  { q: "Kenapa pohon kelapa di depan rumah harus ditebang?", a: "karena gak bisa dicabut" },
  { q: "Sapi apa yang warnanya merah muda?", a: "sapi kehabisan nafas" },
  { q: "Tepung apa yang bisa bikin senang?", a: "tepuk tangan" },
  { q: "Kenapa air laut rasanya asin?", a: "karena ikannya pada keringetan" },
  { q: "Bis apa yang bikin bikin heboh satu sekolah?", a: "bisikan tetangga" },
  { q: "Bebek apa yang kalau jalan selalu muter ke kiri?", a: "bebek dikunci stang" },
  { q: "Kera apa yang bikin suasana jadi gak enak?", a: "kerabuhan" },
  { q: "Singa apa yang gak suka makan daging?", a: "singaparna" },
  { q: "Mandi apa yang bikin gak basah?", a: "mandi bola" },
  { q: "Tahu apa yang rasanya asam banget?", a: "tahu-tahu ditinggal nikah" },
  { q: "Kenapa lampu lalu lintas merah artinya berhenti?", a: "kalau biru dikira bluetooth" },
  { q: "Jus apa yang rasanya pahit banget?", a: "jurnal skripsi" },
  { q: "Ayam apa yang bikin orang kaget?", a: "ayam kaget" },
  { q: "Piring apa yang gak bisa dipakai buat makan?", a: "piringan hitam" },
  // Tambahan Masif Baru
  { q: "Telor apa yang kalau diinjak gak pecah?", a: "telor tatoan" },
  { q: "Kipas apa yang ditunggu-tunggu sama orang pas tanggal muda?", a: "kipas gajian" },
  { q: "Sate apa yang rasanya bisa bikin orang nangis?", a: "sate-lah kau pergi dari hidupku" },
  { q: "Hewan apa yang kalau jalan mundur terus?", a: "pantat gajah" },
  { q: "Kenapa nyamuk lebih suka menghisap darah orang ketimbang sirup?", a: "karena gak ada sedotannya" },
  { q: "Pohon apa yang tidak punya daun dan batang?", a: "pohon masalah" },
  { q: "Kenapa sapi kalau makan rumput gak pernah pakai sendok?", a: "soalnya rumput gak ada kuahnya" },
  { q: "Oren apa yang gak bisa dimakan?", a: "oreng gila" },
  { q: "Buah apa yang bikin kita kecanduan?", a: "buahrangkali besok ketemu lagi" },
  { q: "Sepatu apa yang paling tinggi harganya?", a: "sepatuh pada orang tua" }
];

const TEBAKBENDERA = [
  // Southeast Asia
  { q: "🇮🇩", a: "indonesia" },
  { q: "🇲🇾", a: "malaysia" },
  { q: "🇸🇬", a: "singapore" },
  { q: "🇹🇭", a: "thailand" },
  { q: "🇻🇳", a: "vietnam" },
  { q: "🇵🇭", a: "philippines" },
  { q: "🇲🇲", a: "myanmar" },
  { q: "🇰🇭", a: "cambodia" },
  { q: "🇱🇦", a: "laos" },
  { q: "🇧🇳", a: "brunei" },
  { q: "🇹🇱", a: "east timor" },

  // East & South Asia
  { q: "🇯🇵", a: "japan" },
  { q: "🇰🇷", a: "south korea" },
  { q: "🇰🇵", a: "north korea" },
  { q: "🇨🇳", a: "china" },
  { q: "🇹🇼", a: "taiwan" },
  { q: "🇮🇳", a: "india" },
  { q: "🇵🇰", a: "pakistan" },
  { q: "🇧🇩", a: "bangladesh" },
  { q: "🇱🇰", a: "sri lanka" },
  { q: "🇳🇵", a: "nepal" },
  { q: "🇲🇻", a: "maldives" },
  { q: "🇦🇫", a: "afghanistan" },
  { q: "🇧🇹", a: "bhutan" },
  { q: "🇲🇳", a: "mongolia" },
  { q: "🇲🇴", a: "macau" },
  { q: "🇭🇰", a: "hong kong" },

  // Middle East, West & Central Asia
  { q: "🇸🇦", a: "saudi arabia" },
  { q: "🇦🇪", a: "united arab emirates" },
  { q: "🇶🇦", a: "qatar" },
  { q: "🇰🇼", a: "kuwait" },
  { q: "🇮🇷", a: "iran" },
  { q: "🇮🇶", a: "iraq" },
  { q: "🇹🇷", a: "turkey" },
  { q: "🇵🇸", a: "palestine" },
  { q: "🇯🇴", a: "jordan" },
  { q: "🇱🇧", a: "lebanon" },
  { q: "🇴🇲", a: "oman" },
  { q: "🇾🇪", a: "yemen" },
  { q: "🇰🇿", a: "kazakhstan" },
  { q: "🇰🇬", a: "kyrgyzstan" },
  { q: "🇹🇯", a: "tajikistan" },
  { q: "🇹🇲", a: "turkmenistan" },
  { q: "🇺🇿", a: "uzbekistan" },

  // Western, Northern & Micro European States
  { q: "🇬🇧", a: "united kingdom" },
  { q: "🇫🇷", a: "france" },
  { q: "🇩🇪", a: "germany" },
  { q: "🇳🇱", a: "netherlands" },
  { q: "🇧🇪", a: "belgium" },
  { q: "🇨🇭", a: "switzerland" },
  { q: "🇦🇹", a: "austria" },
  { q: "🇮🇪", a: "ireland" },
  { q: "🇸🇪", a: "sweden" },
  { q: "🇳🇴", a: "norway" },
  { q: "🇩🇰", a: "denmark" },
  { q: "🇫🇮", a: "finland" },
  { q: "🇮🇸", a: "iceland" },
  { q: "🇱🇺", a: "luxembourg" },
  { q: "🇲🇨", a: "monaco" },
  { q: "🇦🇩", a: "andorra" },
  { q: "🇸🇲", a: "san marino" },
  { q: "🇱🇮", a: "liechtenstein" },
  { q: "🇻🇦", a: "vatican city" },
  { q: "🇲🇹", a: "malta" },

  // Southern, Eastern Europe, Baltics & Caucasus
  { q: "🇮🇹", a: "italy" },
  { q: "🇪🇸", a: "spain" },
  { q: "🇵🇹", a: "portugal" },
  { q: "🇬🇷", a: "greece" },
  { q: "🇷🇺", a: "russia" },
  { q: "🇺🇦", a: "ukraine" },
  { q: "🇵🇱", a: "poland" },
  { q: "🇨🇿", a: "czech republic" },
  { q: "🇭🇺", a: "hungary" },
  { q: "🇷🇴", a: "romania" },
  { q: "🇭🇷", a: "croatia" },
  { q: "🇸🇰", a: "slovakia" },
  { q: "🇸🇮", a: "slovenia" },
  { q: "🇷🇸", a: "serbia" },
  { q: "🇧🇬", a: "bulgaria" },
  { q: "🇧🇾", a: "belarus" },
  { q: "🇪🇪", a: "estonia" },
  { q: "🇱🇻", a: "latvia" },
  { q: "🇱🇹", a: "lithuania" },
  { q: "🇲🇩", a: "moldova" },
  { q: "🇦🇱", a: "albania" },
  { q: "🇧🇦", a: "bosnia and herzegovina" },
  { q: "🇲🇪", a: "montenegro" },
  { q: "🇲🇰", a: "north macedonia" },
  { q: "🇦🇲", a: "armenia" },
  { q: "🇦🇿", a: "azerbaijan" },
  { q: "🇬🇪", a: "georgia" },

  // North, Central America & Caribbean
  { q: "🇺🇸", a: "united states" },
  { q: "🇨🇦", a: "canada" },
  { q: "🇲🇽", a: "mexico" },
  { q: "🇯🇲", a: "jamaica" },
  { q: "🇨🇺", a: "cuba" },
  { q: "🇨🇷", a: "costa rica" },
  { q: "🇵🇦", a: "panama" },
  { q: "🇭🇹", a: "haiti" },
  { q: "🇩🇴", a: "dominican republic" },
  { q: "🇬🇹", a: "guatemala" },
  { q: "🇧🇸", a: "bahamas" },
  { q: "🇧🇧", a: "barbados" },
  { q: "🇧🇿", a: "belize" },
  { q: "🇸🇻", a: "el salvador" },
  { q: "🇭🇳", a: "honduras" },
  { q: "🇳🇮", a: "nicaragua" },
  { q: "🇹🇹", a: "trinidad and tobago" },
  { q: "🇦🇬", a: "antigua and barbuda" },
  { q: "🇩🇲", a: "dominica" },
  { q: "🇬🇩", a: "grenada" },
  { q: "🇰🇳", a: "saint kitts and nevis" },
  { q: "🇱🇨", a: "saint lucia" },
  { q: "🇻🇨", a: "saint vincent and the grenadines" },

  // South America
  { q: "🇧🇷", a: "brazil" },
  { q: "🇦🇷", a: "argentina" },
  { q: "🇨🇱", a: "chile" },
  { q: "🇨🇴", a: "colombia" },
  { q: "🇵🇪", a: "peru" },
  { q: "🇺🇾", a: "uruguay" },
  { q: "🇵🇾", a: "paraguay" },
  { q: "🇻🇪", a: "venezuela" },
  { q: "🇪🇨", a: "ecuador" },
  { q: "🇧🇴", a: "bolivia" },
  { q: "🇬🇾", a: "guyana" },
  { q: "🇸🇷", a: "suriname" },

  // Africa
  { q: "🇪🇬", a: "egypt" },
  { q: "🇲🇦", a: "morocco" },
  { q: "🇿🇦", a: "south africa" },
  { q: "🇳🇬", a: "nigeria" },
  { q: "🇰🇪", a: "kenya" },
  { q: "🇩🇿", a: "algeria" },
  { q: "🇹🇳", a: "tunisia" },
  { q: "🇬🇭", a: "ghana" },
  { q: "🇸🇳", a: "senegal" },
  { q: "🇨🇲", a: "cameroon" },
  { q: "🇪🇹", a: "ethiopia" },
  { q: "🇿🇼", a: "zimbabwe" },
  { q: "🇲🇬", a: "madagascar" },
  { q: "🇨🇩", a: "democratic republic of the congo" },
  { q: "🇨🇮", a: "ivory coast" },
  { q: "🇱🇾", a: "libya" },
  { q: "🇸🇩", a: "sudan" },
  { q: "🇸🇸", a: "south sudan" },
  { q: "🇲🇷", a: "mauritania" },
  { q: "🇲🇱", a: "mali" },
  { q: "🇧🇫", a: "burkina faso" },
  { q: "🇳🇪", a: "niger" },
  { q: "🇹🇩", a: "chad" },
  { q: "🇬🇳", a: "guinea" },
  { q: "🇬🇼", a: "guinea-bissau" },
  { q: "🇸🇱", a: "sierra leone" },
  { q: "🇱🇷", a: "liberia" },
  { q: "🇹🇬", a: "togo" },
  { q: "🇧🇯", a: "benin" },
  { q: "🇨🇻", a: "cape verde" },
  { q: "🇬🇶", a: "equatorial guinea" },
  { q: "🇸🇹", a: "sao tome and principe" },
  { q: "🇨🇫", a: "central african republic" },
  { q: "🇬🇦", a: "gabon" },
  { q: "🇨🇬", a: "republic of the congo" },
  { q: "🇦🇴", a: "angola" },
  { q: "🇪🇷", a: "eritrea" },
  { q: "🇩🇯", a: "djibouti" },
  { q: "🇸🇴", a: "somalia" },
  { q: "🇺🇬", a: "uganda" },
  { q: "🇷🇼", a: "rwanda" },
  { q: "🇧🇮", a: "burundi" },
  { q: "🇹🇿", a: "tanzania" },
  { q: "🇲🇿", a: "mozambique" },
  { q: "🇿🇲", a: "zambia" },
  { q: "🇲🇼", a: "malawi" },
  { q: "🇳🇦", a: "namibia" },
  { q: "🇧🇼", a: "botswana" },
  { q: "🇸🇿", a: "eswatini" },
  { q: "🇱🇸", a: "lesotho" },
  { q: "🇲🇺", a: "mauritius" },
  { q: "🇰🇲", a: "comoros" },
  { q: "🇸🇨", a: "seychelles" },

  // Oceania
  { q: "🇦🇺", a: "australia" },
  { q: "🇳🇿", a: "new zealand" },
  { q: "🇫🇯", a: "fiji" },
  { q: "🇵🇬", a: "papua new guinea" },
  { q: "🇼🇸", a: "samoa" },
  { q: "🇹🇴", a: "tonga" },
  { q: "🇻🇺", a: "vanuatu" },
  { q: "🇸🇧", a: "solomon islands" },
  { q: "🇰🇮", a: "kiribati" },
  { q: "🇲🇭", a: "marshall islands" },
  { q: "🇫🇲", a: "micronesia" },
  { q: "🇳🇷", a: "nauru" },
  { q: "🇵🇼", a: "palau" },
  { q: "🇹🇻", a: "tuvalu" }
];

const TEBAKKATA = [
  { q: "Alat buat nulis, isinya tinta", a: "pulpen" },
  { q: "Hewan berbelalai panjang, telinganya besar", a: "gajah" },
  { q: "Tempat nyimpen uang di bank", a: "rekening" },
  { q: "Alat masak buat gorengan, bentuknya cekung", a: "wajan" },
  { q: "Benda langit yang muncul malam hari, banyak jumlahnya", a: "bintang" },
  { q: "Kendaraan roda dua yang dikayuh", a: "sepeda" },
  { q: "Tempat orang belajar dari SD sampai SMA", a: "sekolah" },
  { q: "Alat buat lihat waktu, dipakai di tangan", a: "jam tangan" },
  { q: "Alat untuk mendinginkan ruangan secara cepat", a: "ac" },
  { q: "Cairan merah yang mengalir di tubuh manusia", a: "darah" },
  { q: "Penutup kepala yang biasa dipakai saat naik motor", a: "helm" },
  { q: "Tempat mendarat dan lepas landas pesawat terbang", a: "bandara" },
  { q: "Benda kaca yang bisa memantulkan bayangan diri", a: "cermin" },
  { q: "Alat pelindung diri dari hujan atau panas terik", a: "payung" },
  { q: "Tempat menyimpan pakaian di dalam kamar", a: "lemari" },
  { q: "Cairan manis yang dihasilkan oleh lebah", a: "madu" },
  { q: "Benda berbahan kain tempat menaruh kepala saat tidur", a: "bantal" },
  { q: "Hewan amfibi yang pandai melompat dan bersuara nyaring saat hujan", a: "katak" },
  { q: "Pakaian luar hangat berkancing atau berresleting", a: "jaket" },
  { q: "Lampu lalu lintas untuk mengatur kendaraan di jalan raya", a: "marka" },
  { q: "Papan ketik pada komputer atau laptop", a: "keyboard" },
  { q: "Penyedap rasa asin putih yang dibuat dari air laut", a: "garam" },
  { q: "Alat potong tajam berbilah baja di dapur", a: "pisau" },
  { q: "Tempat untuk meminjam dan membaca buku secara gratis", a: "perpustakaan" },
  { q: "Lembaga tempat perawatan orang sakit oleh dokter", a: "rumah sakit" },
  { q: "Sepatu beroda yang dipakai untuk meluncur", a: "sepatu roda" },
  { q: "Alat untuk merekam suara dan video digital", a: "kamera" },
  { q: "Ikan konsumsi bertubuh pipih dengan rasa gurih manis", a: "gurame" },
  { q: "Alat penerangan kecil yang menggunakan baterai", a: "senter" },
  { q: "Daun hijau aromatik khas masakan Italia", a: "basil" },
  { q: "Bagian kendaraan untuk mengarahkan laju ke kiri atau kanan", a: "setir" },
  { q: "Alat peniup udara hangat untuk mengeringkan rambut", a: "pengering rambut" },
  { q: "Batu berharga berwarna hijau transparan", a: "zamrud" },
  { q: "Pakaian tradisional wanita Indonesia berbahan kain tipis", a: "kebaya" },
  { q: "Roti berbentuk melingkar dengan lubang di tengahnya", a: "donat" },
  // Tambahan Masif Baru
  { q: "Perhiasan berbentuk lingkaran melingkar di jari", a: "cincin" },
  { q: "Bumbuan manis cair kental berwarna cokelat kehitaman", a: "kecap" },
  { q: "Hewan melata bersisik yang tidak memiliki kaki", a: "ular" },
  { q: "Kain lebar penutup kasur tidur", a: "sprei" },
  { q: "Tempat persinggahan utama kereta api", a: "stasiun" },
  { q: "Alat makan bertangkai dengan lekukan berbentuk mangkuk kecil", a: "sendok" },
  { q: "Benda pembungkus surat atau dokumen penting", a: "amplop" },
  { q: "Hewan pemakan daging bersuara mengaum keras", a: "singa" },
  { q: "Tempat olahraga yang memiliki lapangan hijau luas", a: "stadion" },
  { q: "Alat pengukur suhu tubuh manusia", a: "termometer" }
];

const SUSUNKATA_WORDS = [
  "komputer", "matahari", "keyboard", "pelangi", "gunung",
  "samudra", "bintang", "kupukupu", "sepatu", "jendela",
  "kalender", "payung", "handphone", "cermin", "gerbang",
  "perahu", "pesawat", "istana", "kelinci", "stasiun",
  "dompet", "kacamata", "pantai", "domino", "lukisan",
  "kamera", "sepeda", "piring", "lemari", "cangkir",
  "sendok", "televisi", "selimut", "tangga", "mahkota",
  "sekolah", "bendera", "domba", "sandal", "panci",
  "pensil", "kertas", "kompor", "laptop", "mangkuk",
  "termos", "kincir", "stempel", "perisai", "trompet",
  "mentari", "kereta", "majalah", "seruling",
  // Tambahan Masif Baru
  "piramida", "angkasa", "harimau", "nelayan", "prajurit",
  "kelapa", "pantofel", "suling", "kelereng", "teropong"
];

const TEBAKPRESIDEN = [
  { q: "Presiden pertama RI, proklamator kemerdekaan Indonesia", a: "soekarno" },
  { q: "Presiden kedua RI, menjabat paling lama (32 tahun)", a: "soeharto" },
  { q: "Presiden ke-3 RI, dikenal sebagai bapak teknologi Indonesia", a: "habibie" },
  { q: "Presiden ke-4 RI, dikenal sebagai bapak pluralisme", a: "gus dur" },
  { q: "Presiden wanita pertama RI", a: "megawati" },
  { q: "Presiden ke-6 RI, dari partai demokrat, 2 periode", a: "sby" },
  { q: "Presiden ke-7 RI, mantan Gubernur DKI Jakarta", a: "jokowi" },
  { q: "Presiden ke-8 RI, mantan menteri pertahanan", a: "prabowo" },
  { q: "Presiden Amerika Serikat pertama", a: "washington" },
  { q: "Presiden Amerika Serikat ke-16 yang membebaskan budak", a: "lincoln" },
  { q: "Presiden Rusia yang menjabat saat ini", a: "putin" },
  { q: "Presiden Turki yang menjabat saat ini", a: "erdogan" },
  { q: "Presiden AS saat peristiwa Perang Dunia II berakhir (1945)", a: "truman" },
  { q: "Presiden Amerika Serikat ke-35 yang tewas ditembak di Dallas", a: "kennedy" },
  { q: "Presiden Prancis yang menjabat saat ini", a: "macron" },
  { q: "Presiden pertama Afrika Selatan pasca-apartheid", a: "mandela" },
  { q: "Presiden pertama Filipina", a: "aguinaldo" },
  { q: "Presiden Amerika Serikat kulit hitam pertama", a: "obama" },
  { q: "Presiden China saat ini yang juga menjabat Sekretaris Jenderal PKC", a: "xi jinping" },
  { q: "Presiden Korea Selatan yang menjabat saat ini", a: "yoon suk yeol" },
  { q: "Presiden Brasil yang memenangkan pemilu 2022", a: "lula" },
  { q: "Presiden Ukraina yang memimpin saat konflik Rusia-Ukraina", a: "zelensky" },
  { q: "Presiden Amerika Serikat ke-40 yang merupakan mantan aktor Hollywood", a: "reagan" },
  { q: "Presiden Amerika Serikat ke-26 yang terkenal dengan kebijakan Big Stick", a: "roosevelt" },
  { q: "Presiden pertama Singapura", a: "yusof ishak" },
  // Tambahan Masif Baru
  { q: "Presiden pertama Mesir yang memimpin revolusi 1952", a: "nasser" },
  { q: "Presiden pertama Timor Leste setelah merdeka dari Indonesia", a: "xanana gusmao" },
  { q: "Presiden Argentina yang memenangkan pemilu presiden 2023", a: "javier milei" },
  { q: "Presiden Meksiko yang menjabat dari tahun 2018", a: "amlo" },
  { q: "Presiden AS ke-32 yang memimpin selama Depresi Besar dan Perang Dunia II", a: "fdr" }
];

const TEBAKPOKEMON = [
  { q: "Pokemon api starter Kanto, evolusi akhirnya Charizard", a: "charmander" },
  { q: "Tikus listrik kuning, maskot utama franchise Pokemon", a: "pikachu" },
  { q: "Pokemon air starter Kanto, bentuk kura-kura", a: "squirtle" },
  { q: "Pokemon rumput starter Kanto, ada bunga di punggung pas evolusi", a: "bulbasaur" },
  { q: "Pokemon psikis legendaris, hasil eksperimen kloning dari Mew", a: "mewtwo" },
  { q: "Pokemon hantu ungu, sering nyengir jahil", a: "gengar" },
  { q: "Pokemon normal yang bisa berevolusi jadi banyak tipe beda", a: "eevee" },
  { q: "Pokemon pemalas yang sukanya tidur dan menghalangi jalan", a: "snorlax" },
  { q: "Pokemon bebek yang sering pusing kepala lalu mengeluarkan kekuatan psikis", a: "psyduck" },
  { q: "Pokemon naga oranye besar yang awalnya dianggap ikan lemah Magikarp", a: "gyarados" },
  { q: "Pokemon anjing api yang bisa berevolusi memakai Fire Stone", a: "growlithe" },
  { q: "Pokemon burung legendaris bertipe es dan terbang", a: "articuno" },
  { q: "Pokemon burung legendaris bertipe petir dan terbang", a: "zapdos" },
  { q: "Pokemon burung legendaris bertipe api dan terbang", a: "moltres" },
  { q: "Pokemon naga legendaris penyeimbang cuaca dari wilayah Hoenn", a: "rayquaza" },
  { q: "Pokemon peniruan yang bisa berubah bentuk jadi Pokemon lawan", a: "ditto" },
  { q: "Pokemon tipe psikis penjelajah waktu berbentuk peri hijau kecil", a: "celebi" },
  { q: "Pokemon tipe air berpenampilan lumba-lumba/paus biru raksasa legendaris", a: "kyogre" },
  { q: "Pokemon tipe tanah raksasa legendaris pencipta daratan dari Hoenn", a: "groudon" },
  { q: "Pokemon besi dan naga yang memiliki kekuatan mengendalikan waktu", a: "dialga" },
  { q: "Pokemon starter api wilayah Johto berbentuk musang", a: "cyndaquil" },
  { q: "Pokemon starter air wilayah Johto berbentuk buaya", a: "totodile" },
  { q: "Pokemon starter rumput wilayah Johto berbentuk daun", a: "chikorita" },
  { q: "Pokemon penjelajah waktu bertipe naga dan ruang dari Sinnoh", a: "palkia" },
  { q: "Pokemon legenda tipe bayangan dan naga penjaga dunia terbalik", a: "giratina" },
  // Tambahan Masif Baru
  { q: "Pokemon serangga starter Kanto berbentuk ulat hijau", a: "caterpie" },
  { q: "Evolusi akhir dari Eevee jika menggunakan Water Stone", a: "vaporeon" },
  { q: "Evolusi akhir dari Eevee jika menggunakan Thunder Stone", a: "jolteon" },
  { q: "Evolusi akhir dari Eevee jika menggunakan Fire Stone", a: "flareon" },
  { q: "Pokemon rubah ber-ekor enam tipe api dari Kanto", a: "vulpix" }
];

const KUISISLAMI = [
  { q: "Rukun Islam yang kelima (terakhir) adalah...", a: "haji" },
  { q: "Nabi terakhir dan penutup para nabi adalah Nabi...", a: "muhammad" },
  { q: "Puasa wajib yang dilakukan pada bulan ke-9 kalender Hijriah disebut puasa...", a: "ramadhan" },
  { q: "Zakat yang wajib dikeluarkan menjelang Idul Fitri disebut zakat...", a: "fitrah" },
  { q: "Kitab suci umat Islam bernama...", a: "al quran" },
  { q: "Rukun iman yang keenam (terakhir) adalah iman kepada qada dan...", a: "qadar" },
  { q: "Peristiwa perjalanan malam Nabi Muhammad dari Mekah ke Baitul Maqdis lalu naik ke langit disebut...", a: "isra miraj" },
  { q: "Perang pertama umat Islam melawan kaum Quraisy yang terjadi di dekat sebuah sumur bernama Perang...", a: "badar" },
  { q: "Wahyu pertama yang diturunkan kepada Nabi Muhammad adalah surat Al-'Alaq ayat...", a: "1 5" },
  { q: "Hukum menikah bagi seseorang yang sudah mampu dan takut terjerumus zina adalah...", a: "wajib" },
  { q: "Kitab suci yang diturunkan kepada Nabi Daud AS adalah...", a: "zabur" },
  { q: "Shalat sunnah yang dilakukan khusus pada malam bulan Ramadhan adalah shalat...", a: "tarawih" },
  { q: "Gelar Al-Amin yang diberikan masyarakat Quraisy kepada Nabi Muhammad artinya orang yang...", a: "dapat dipercaya" },
  { q: "Sifat wajib bagi rasul yang berarti menyampaikan adalah...", a: "tabligh" },
  { q: "Malaikat yang bertugas mencatat amal baik manusia adalah malaikat...", a: "raqib" },
  { q: "Malaikat yang bertugas mencatat amal buruk manusia adalah malaikat...", a: "atid" },
  { q: "Malaikat yang bertugas menyampaikan wahyu adalah malaikat...", a: "jibril" },
  { q: "Gelar khulafaur rasyidin yang diberikan kepada Abu Bakar adalah...", a: "as shiddiq" },
  { q: "Gelar sahabat Umar bin Khattab yang berarti pembeda antara hak dan batil adalah...", a: "al faruq" },
  { q: "Nama paman Nabi Muhammad yang gugur dan menjadi syahid dalam Perang Uhud adalah...", a: "hamzah" },
  { q: "Bulan pertama dalam kalender Hijriah adalah bulan...", a: "muharram" },
  { q: "Kota tempat Nabi Muhammad SAW melakukan hijrah dari Mekah dinamakan...", a: "madinah" },
  { q: "Suci dari hadas kecil dapat dicapai dengan cara melakukan...", a: "wudhu" },
  { q: "Pengganti wudhu saat tidak menemukan air menggunakan debu yang suci disebut...", a: "tayamum" },
  { q: "Tempat ibadah khusus bagi umat Islam disebut...", a: "masjid" },
  { q: "Jumlah juz dalam Al-Quran seluruhnya ada...", a: "30" },
  { q: "Surat pendek dalam Al-Quran yang menyamai sepertiga Al-Quran adalah Al-...", a: "ikhlas" },
  { q: "Nabi yang diberi mukjizat tidak terbakar oleh api adalah Nabi...", a: "ibrahim" },
  { q: "Nabi yang mendapat gelar Kalimullah (orang yang diseru Allah langsung) adalah Nabi...", a: "musa" },
  { q: "Malaikat yang bertugas mencabut nyawa seluruh makhluk hidup adalah malaikat...", a: "izrail" },
  // Tambahan Masif Baru
  { q: "Kitab suci yang diturunkan kepada Nabi Isa AS adalah...", a: "injil" },
  { q: "Kitab suci yang diturunkan kepada Nabi Musa AS adalah...", a: "taurat" },
  { q: "Malaikat yang bertugas meniup sangkakala pada hari kiamat adalah malaikat...", a: "israfil" },
  { q: "Surat terpanjang di dalam Al-Quran adalah surat Al-...", a: "baqarah" },
  { q: "Peristiwa turunnya Al-Quran untuk pertama kalinya disebut Nuzulul...", a: "quran" }
];

const KUISMTK = [
  { q: "Nilai dari lim(x→2) (x²-4)/(x-2) adalah...", a: "4" },
  { q: "Diketahui f(x) = x² - 4x + 3. Nilai x saat f'(x) = 0 adalah...", a: "2" },
  { q: "Determinan dari matriks [[2,3],[1,4]] adalah...", a: "5" },
  { q: "Median dari data: 3, 5, 7, 8, 9, 10, 12 adalah...", a: "8" },
  { q: "Banyaknya cara menyusun huruf dari kata 'MATA' (ada 2 huruf A yang sama) adalah...", a: "12" },
  { q: "Nilai dari ²log8 + ²log4 adalah...", a: "5" },
  { q: "Jumlah 5 suku pertama deret aritmatika dengan suku pertama 2 dan beda 3 adalah...", a: "40" },
  { q: "Peluang keluar mata dadu genap saat melempar 1 dadu adalah a/b (paling sederhana). Berapa a+b?", a: "3" },
  { q: "Turunan dari f(x) = 5x³ pada x = 1 adalah f'(1) = ...", a: "15" },
  { q: "Jika vektor a = (3,4), panjang (besar) vektor a adalah...", a: "5" },
  { q: "Nilai dari sin(30°) + cos(60°) adalah...", a: "1" },
  { q: "Suku ke-10 dari barisan aritmatika 2, 5, 8, 11, ... adalah...", a: "29" },
  { q: "Integral dari ∫ (2x) dx adalah x² + C. Jika x = 3, maka x² = ...", a: "9" },
  { q: "Nilai dari 3! (3 faktorial) adalah...", a: "6" },
  { q: "Jika 2^(x) = 16, nilai x adalah...", a: "4" },
  { q: "Hasil perkalian matriks identitas 2x2 dengan matriks apapun akan menghasilkan matriks itu sendiri. Jika elemen diagonal matriks identitas dijumlahkan, nilainya adalah...", a: "2" },
  { q: "Persamaan x² - 9 = 0 memiliki dua akar real. Jumlah kedua akar tersebut (x1 + x2) adalah...", a: "0" },
  { q: "Berapa hasil dari 5! / 4! ?", a: "5" },
  { q: "Panjang sisi miring segitiga siku-siku dengan alas 6 cm dan tinggi 8 cm adalah...", a: "10" },
  { q: "Modus dari data: 2, 4, 4, 5, 6, 7, 8, 4, 9 adalah...", a: "4" },
  { q: "Nilai dari cos(0°) adalah...", a: "1" },
  { q: "Jika log 100 = x, berapa nilai x?", a: "2" },
  { q: "Turunan pertama dari f(x) = 7x + 3 adalah...", a: "7" },
  { q: "Luas lingkaran dengan jari-jari 7 cm (π = 22/7) adalah...", a: "154" },
  { q: "Volume kubus yang panjang rusuknya 4 cm adalah...", a: "64" },
  { q: "Berapakah nilai dari √144?", a: "12" },
  { q: "Berapakah jumlah derajat sudut dalam sebuah segitiga?", a: "180" },
  { q: "Berapa hasil perkalian dari 15 x 6?", a: "90" },
  { q: "Jika f(x) = 2x + 5, maka nilai f(3) adalah...", a: "11" },
  { q: "Nilai dari tan(45°) adalah...", a: "1" },
  // Tambahan Masif Baru
  { q: "Nilai dari sin(90°) adalah...", a: "1" },
  { q: "Hasil penjumlahan sudut berpenyiku adalah ... derajat", a: "90" },
  { q: "Luas persegi dengan keliling 20 cm adalah...", a: "25" },
  { q: "Akar-akar dari x² - 5x + 6 = 0 adalah x=2 dan x=...", a: "3" },
  { q: "Nilai dari 4! adalah...", a: "24" }
];

const TERASAURUS = [
  { word: "senang", sinonim: "gembira", antonim: "sedih", lain: ["meja", "lari", "biru"] },
  { word: "besar", sinonim: "raksasa", antonim: "kecil", lain: ["sepatu", "dingin", "cepat"] },
  { word: "cepat", sinonim: "kilat", antonim: "lambat", lain: ["gunung", "manis", "hujan"] },
  { word: "tinggi", sinonim: "menjulang", antonim: "rendah", lain: ["pintu", "lapar", "kertas"] },
  { word: "gelap", sinonim: "kelam", antonim: "terang", lain: ["kursi", "manis", "angin"] },
  { word: "kuat", sinonim: "perkasa", antonim: "lemah", lain: ["jendela", "hujan", "kelinci"] },
  { word: "rajin", sinonim: "giat", antonim: "malas", lain: ["piring", "laut", "sepeda"] },
  { word: "berani", sinonim: "gagah", antonim: "takut", lain: ["buku", "batu", "hijau"] },
  { word: "jujur", sinonim: "tulus", antonim: "bohong", lain: ["meja", "api", "pensil"] },
  { word: "kaya", sinonim: "berada", antonim: "miskin", lain: ["awan", "roti", "jam"] },
  { word: "panas", sinonim: "terik", antonim: "dingin", lain: ["sungai", "kabel", "cermin"] },
  { word: "mudah", sinonim: "gampang", antonim: "sulit", lain: ["piano", "jaket", "sepatu"] },
  { word: "baik", sinonim: "ramah", antonim: "jahat", lain: ["lampu", "tas", "gula"] },
  { word: "cantik", sinonim: "molek", antonim: "jelek", lain: ["kayu", "motor", "pisau"] },
  { word: "banyak", sinonim: "berlimpah", antonim: "sedikit", lain: ["rumah", "kucing", "telepon"] },
  { word: "bahagia", sinonim: "riang", antonim: "murung", lain: ["pohon", "kertas", "gelas"] },
  { word: "luas", sinonim: "lapang", antonim: "sempit", lain: ["sendok", "merah", "tidur"] },
  { word: "pinter", sinonim: "cerdas", antonim: "bodoh", lain: ["sepatu", "awan", "ember"] },
  { word: "harum", sinonim: "wangi", antonim: "bau", lain: ["kursi", "hujan", "pintu"] },
  { word: "pagi", sinonim: "fajar", antonim: "malam", lain: ["buku", "garpu", "pisau"] },
  { word: "sahabat", sinonim: "kawan", antonim: "musuh", lain: ["piring", "kabel", "batu"] },
  { word: "bersih", sinonim: "higienis", antonim: "kotor", lain: ["topi", "pintu", "papan"] },
  { word: "murah", sinonim: "terjangkau", antonim: "mahal", lain: ["awan", "singa", "roti"] },
  { word: "lapar", sinonim: "dahaga", antonim: "kenyang", lain: ["buku", "jam", "lantai"] },
  { word: "basah", sinonim: "lembap", antonim: "kering", lain: ["sendok", "kertas", "meja"] },
  { word: "segar", sinonim: "bugar", antonim: "layu", lain: ["pintu", "cangkir", "pagar"] },
  { word: "lembut", sinonim: "halus", antonim: "kasar", lain: ["batu", "lampu", "roda"] },
  { word: "panjang", sinonim: "molor", antonim: "pendek", lain: ["pohon", "kucing", "kertas"] },
  { word: "ramai", sinonim: "bising", antonim: "sepi", lain: ["lemari", "sepatu", "pisau"] },
  { word: "dalam", sinonim: "jeluk", antonim: "dangkal", lain: ["awan", "garpu", "sendok"] },
  // Tambahan Masif Baru
  { word: "manis", sinonim: "nira", antonim: "pahit", lain: ["sendok", "batu", "gelas"] },
  { word: "baru", sinonim: "gres", antonim: "lama", lain: ["kabel", "pintu", "lampu"] },
  { word: "terang", sinonim: "benderang", antonim: "gelap", lain: ["sepatu", "tas", "ember"] },
  { word: "ramah", sinonim: "supel", antonim: "judes", lain: ["pensil", "roda", "papan"] },
  { word: "gemuk", sinonim: "subur", antonim: "kurus", lain: ["kertas", "meja", "kucing"] }
];
const KUISKRISTEN = [
  // Original
  { q: "Kitab suci umat Kristen bernama...", a: "alkitab" },
  { q: "Hari raya yang memperingati kelahiran Yesus Kristus disebut...", a: "natal" },
  { q: "Hari raya yang memperingati kebangkitan Yesus Kristus dari kematian disebut...", a: "paskah" },
  { q: "Alkitab terbagi jadi dua bagian besar, yaitu Perjanjian Lama dan Perjanjian...", a: "baru" },
  { q: "Kedua belas pengikut utama Yesus Kristus disebut kedua belas...", a: "rasul" },
  { q: "Perayaan turunnya Roh Kudus, 50 hari setelah Paskah, disebut hari raya...", a: "pentakosta" },
  { q: "Sepuluh ... Allah yang diterima Nabi Musa di Gunung Sinai jadi dasar hukum moral dalam Alkitab.", a: "perintah" },
  { q: "Kota kelahiran Yesus Kristus, menurut catatan Alkitab, adalah...", a: "betlehem" },
  { q: "Murid yang mengkhianati Yesus Kristus dengan menyerahkannya ke penguasa, bernama Yudas...", a: "iskariot" },
  { q: "Doa yang diajarkan langsung oleh Yesus kepada murid-muridnya dikenal sebagai Doa...", a: "bapa kami" },

  // Expansion
  { q: "Kitab pertama dalam Alkitab Perjanjian Lama adalah...", a: "kejadian" },
  { q: "Kitab terakhir dalam Alkitab Perjanjian Baru adalah...", a: "wahyu" },
  { q: "Ibu dari Yesus Kristus bernama...", a: "maria" },
  { q: "Ayah angkat Yesus yang bekerja sebagai tukang kayu bernama...", a: "yusuf" },
  { q: "Lautan yang dibelah oleh Musa atas pertolongan Tuhan bernama Laut...", a: "tebrau" },
  { q: "Raja Israel yang mengalahkan raksasa Goliat bernama...", a: "daud" },
  { q: "Jumlah Injil utama dalam Perjanjian Baru ada...", a: "empat" },
  { q: "Sungai tempat Yesus dibaptis oleh Yohanes Pembaptis adalah Sungai...", a: "yordan" },
  { q: "Nabi yang ditelan oleh ikan besar karena mencoba melarikan diri dari perintah Tuhan adalah...", a: "yunus" },
  { q: "Tempat Yesus disalibkan yang memiliki arti 'tempat tengkorak' disebut...", a: "golgota" },
  { q: "Bahtera raksasa untuk menyelamatkan manusia dan hewan dari air bah dibangun oleh...", a: "nuh" },
  { q: "Murid Yesus yang menyangkal-Nya tiga kali sebelum ayam berkokok bernama...", a: "petrus" },
  { q: "Perintah utama untuk membaptis dan mengajar semua bangsa dikenal sebagai Amanat...", a: "agung" },
  { q: "Raja yang terkenal paling bijaksana dan membangun Bait Allah pertama di Yerusalem adalah...", a: "salomo" },
  { q: "Pengikut Kristus pertama kali disebut 'Orang Kristen' di kota...", a: "antiokhia" }
];

module.exports = {
  ASAHOTAK,
  TEBAKTEBAKAN,
  TEBAKBENDERA,
  TEBAKKATA,
  SUSUNKATA_WORDS,
  TEBAKPRESIDEN,
  TEBAKPOKEMON,
  KUISISLAMI,
  KUISKRISTEN,
  KUISMTK,
  TERASAURUS,
};
